# Local/dev overrides (non-Nitro).
CHANNEL_TYPE=tcp
EXECUTOR_PORT=4000
EXECUTOR_IP_HOST=127.0.0.1
LOG_SERVER_IP_HOST=127.0.0.1
EXECUTOR_LOG_NETWORK_LEVEL=info

# KMS disabled for local/dev
EXECUTOR_KEYSET_RECOVERY_TYPE=0
