BlockchainPollingInterval=5
ExecutorConnectionType=tcp
ExecutorConnectionUrl=localhost:8080
RpcUrl=http://127.0.0.1:8545
PrivateKey=5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
ProcessorAddress=0xCfEB869F69431e42cd62bB3aB5De8C3fB4d92dB
KeyRegistryAddress=0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
MockBlockChainClient=false,
DataLayerType=versioned_leveldb
DataLayerDBPath=/tmp/horizen-pes-data/manager_db
DataLayerNumOfVersions=10