CHANNEL_TYPE=tcp

# Admin command server settings
MANAGER_ADMIN_PORT=4002
MANAGER_IP_HOST=localhost

CHAIN_PROCESSOR_ADDRESS=0x0000000000000000000000000000000000000000
CHAIN_TEEAUTHENTICATOR_ADDRESS=0x0000000000000000000000000000000000000000
MANAGER_DATA_FOLDER=/tmp/vela-data/manager_db
LOG_SERVER_FILE_NAME=/tmp/log_server.log
MANAGER_REPORTS_FOLDER=/tmp/vela-data/manager_reports
# Shared artifact path (must point to same underlying volume/path used by authorityservice DEPLOY_ARTIFACTS_PATH)
MANAGER_ARTIFACTS_PATH=/tmp/vela-data/deploy_artifacts
