CHANNEL_TYPE=tcp
CHAIN_PROCESSOR_ADDRESS=0x0000000000000000000000000000000000000000
CHAIN_TEEAUTHENTICATOR_ADDRESS=0x0000000000000000000000000000000000000000
MANAGER_DATA_FOLDER=/tmp/horizen-pes-data/manager_db
LOG_SERVER_FILE_NAME=/tmp/log_server.log
LOG_SERVER_FILE_LEVEL=trace
MANAGER_REPORTS_FOLDER=/tmp/horizen-pes-data/manager_reports
